baseURL = "https://mubon-esg.github.io/Debrah/"
languageCode = "zh-tw"
title = "Debrah ESG Procurement Performance｜永續採購顧問"
theme = "PaperMod"

disableKinds = []

[outputs]
home = ["HTML"]
section = ["HTML"]
page = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[taxonomies]
tag = "tags"
category = "categories"

[params]
env = "production"




















