baseURL = "https://mubon-esg.github.io/Debrah/"
languageCode = "zh-tw"
title = "Debrah ESG Procurement Performance｜永續採購顧問"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
env = "production"

[taxonomies]
tag = "tags"
category = "categories"





 













































