baseURL = 'https://mubon-esg.github.io/debrah/'
minify = false  # 先關掉壓縮，方便我們除錯
languageCode = 'zh-tw'
title = 'Debrah ESG Procurement Performance Coach'
theme = 'PaperMod'

[params]
    env = "production"

[params.homeInfoParams]
    Title = "歡迎來到 Debrah 的 ESG 實驗室"
    Content = "這裡記錄了我對永續發展與技術的點滴思考。"

[menu.main]
    [[menu.main]]
        name = "所有文章"
        url = "posts/"
        weight = 10

[params.assets]
    disableHLJS = false


